language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=master

install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

after_success: coveralls
